### PR TITLE
Php connection gets lost when idle after connect

### PR DESCRIPTION
**Pull request by unglaublicherdude**
This is not complete yet. Missing is the Exceptions throw in the EventLoop while no request is running.

### CODE REVIEW

**Comment by unglaublicherdude** [comment]
Ok. This is the first version, where all tests pass.

**Review by lennartdohmann — APPROVED** [review]

**Comment by unglaublicherdude** [comment]
With the update to "amphp/file": "3.1.1" this can now be reviewed.

**Comment by unglaublicherdude** [comment]
The failing run is the Delete old container images and I am not sure, why that runs anyway within this pr.

**Comment by unglaublicherdude** [comment]
Ok. I fixed the delete container images run but I am still not sure, why it runs in this PR (and other PRs aswell)

**Comment by unglaublicherdude** [comment]
I still see one major issue. Illuminate/Container does only support PHP >= 8.2. So I will have to downgrade it to a version that does still support 8.1

**Comment by unglaublicherdude** [comment]
my fault. illuminate/containers is not used and was only in my composer.lock file

**Comment by unglaublicherdude** [comment]
replaced by https://github.com/GDATASoftwareAG/vaas/pull/592

**Pull request closed without merging**
